name: Dead Hosts Infrastructure Workflow
on:
  push:
    branches:
      - "*"
      - "!worker"
  workflow_dispatch: {}

env:
  PYFUNCEBLE_AUTO_CONFIGURATION: "YES"
  GIT_NAME: "${{ secrets.GIT_BOT_NAME }}"
  GIT_EMAIL: "${{ secrets.GIT_BOT_EMAIL }}"
  GIT_BRANCH: "${{ github.head_ref || github.ref_name }}"
  GIT_DISTRIBUTION_BRANCH: "${{ github.head_ref || github.ref_name }}"
  PYFUNCEBLE_CONFIG_DIR: "${{ github.workspace }}/.pyfunceble"
  GITHUB_TOKEN: "${{ secrets.BOT_REPO_PAT }}"
  PLATFORM_API_URL: "${{ secrets.PLATFORM_API_URL }}"
  PLATFORM_API_TOKEN: "${{ secrets.PLATFORM_API_TOKEN }}"
  PLATFORM_SCOPE: "${{ secrets.PLATFORM_SCOPE }}"

jobs:
  single:
    name: Run the Dead Hosts launcher
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.11"
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Clone repository
        with:
          token: "${{ secrets.BOT_REPO_PAT }}"

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          pip install dead-hosts-launcher~=2.3.0

      - name: Get PyFunceble version
        run: |
          PyFunceble --version

      - name: Get Launcher version
        run: |
          dead-hosts-launcher --version

      - name: Run Launcher
        run: |
          dead-hosts-launcher
